theme: jekyll-theme-minimal
title: GalaxyAllie
description: Hi, I'm Allie! This is the personal website of me and where you can learn about Allienet (AS205789) and some of my other hobby projects!
logo: assets/images/portrait-sq-j-web.jpg
