theme: jekyll-theme-minimal
title: GalaxyAllie
description: Allie's random thoughts and musings. All opinions, statements, writing, etc are purely my own and are not endorsed by my employer, my friends, my family, or anyone else!
logo: assets/images/Allie_Image.jpeg